name: Deploy to Clojars

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: "Version in YYYY.M.D format"
        required: false
        default: ""

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          server-id: clojars
          server-username: CLOJARS_USERNAME
          server-password: CLOJARS_PASSWORD

      - name: Install Clojure Tools
        uses: DeLaGuardo/setup-clojure@13.2
        with:
          cli: latest

      - name: Deploy to Clojars
        run: clojure -T:build deploy
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
